[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect rules for Next.js App Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# API redirects for serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Language redirects
[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = false

# Arabic language redirect
[[redirects]]
  from = "/ar/*"
  to = "/ar/:splat"
  status = 200

# English language redirect  
[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
  status = 200

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions configuration
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai"]

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment variables (these will be set in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_SITE_URL = "https://your-site.netlify.app"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_SITE_URL = "https://deploy-preview-$REVIEW_ID--your-site.netlify.app"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_SITE_URL = "https://$BRANCH--your-site.netlify.app"
